### ISSUE TITLE
Add "manual entry" as alternative to meta data selection

### ISSUE THREAD

**Issue by damthor** [flowsforapex/bpmn-modeler#106]
For User Task - Call APEX Page & Service Task - Send Mail (Use Template: Yes) we should allow manual entry of the associated properties (applicationId, pageId, itemName, templateId). When moving models through different environments we can not be sure, that the referenced data can be retrieved using the APEX meta data, resulting in empty select lists despite valid values in the xml.

An additional select box at the top can be used for selecting the "input mode" and to hide/display the correct fields. This view should also be default on opening a diagram/creating a new User Task, so the meta data usage can be seen as an optimization.

- [x] Add select box for input mode
- [x] Add "not_found" entry on select lists when value could not be found using meta data
- [x] Check validation on input fields
- [ ] **EXTRA**: extend the properties (manual + meta data) by a "workspaceId" field to ensure correct reference when using multiple environments
- [ ] **EXTRA**: Add a "default" User Task subtype with no custom attributes (due to removing the empty option in the APEX processes for meta data select lists)
